services:
    dev-postgres:
        image: 'postgres:17'
        restart: unless-stopped
        environment:
            POSTGRES_DB: dev_db
            POSTGRES_PASSWORD: dev_pwd
            POSTGRES_USER: dev
        ports:
            - '5432:5432'
        volumes:
            - dev_db_data:/var/lib/postgresql/data
volumes:
    dev_db_data: